<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="assets/Semantic/semantic.css">
    <link rel="stylesheet" href="estilo.css">
    <link rel="shortcut icon" href="assets/imagens/favicon.ico" type="image/x-icon" />
    <title>Aqui é Perigoso?</title>

</head>
<body>

<!--CABECALHO-->
<div id="cabecalho" class="menu-wrapper ui inverted segment">

    <h1 class="logo"><i class="marker icon"></i>Aqui é <br> Perigoso?</h1>

    <div class="ui inverted secondary pointing menu borderless">
        <a class="item" href="index.html">
            Início
        </a>
        <a class="item" href="mapa.phtml">
            Mapas
        </a>

        <a class="item"   href="noticias.phtml">
            Notícias
        </a>
        <a class="item" href="estatistica.phtml">
            Estatísticas
        </a>
        <a class="item" href="forum.phtml">
            Fórum
        </a>
        <a class="item active" href="empresas.phtml">
            Empresas
        </a>

        <div class="ui buttons">
            <a href="cadastro.phtml"  class="ui button">Registre-se</a>
            <div class="or" data-text="ou"></div>
            <a href="login.phtml" class="ui negative button">Acesse</a>
        </div>
    </div>

</div>
<!-- #CABEÇALHO-->

<!-- CONTEÚDO PRINCIPAL (INFORMAÇÕES E IMAGENS) -->
<div class="ui inverted container" id="principal">

<article class="ui internally grid">

    <div class="row">

        <section class="column four wide">

            <div class="ui inverted">
                <img src="assets/imagens/empresas/tele.jpg" class="ui image">
            </div>
        </section>

        <section class="column four wide">
            <div class="ui inverted">
                <img src="assets/imagens/empresas/segu.jpg" class="ui image" id="img">
            </div>
        </section>

        <section class="column four wide">
            <div class="ui inverted">
                <img src="assets/imagens/empresas/seven.jpg" class="ui image" id="img1">
            </div>
        </section>

        <section class="column four wide">
            <div class="ui inverted">
                <img src="assets/imagens/empresas/garra.jpg" class="ui image" id="img2">
            </div>
        </section>
    </div>
</article>
</div>
<!-- #CONTEÚDO PRINCIPAL (INFORMAÇÕES E IMAGENS) -->

<!-- RODAPÉ -->
<div class="ui inverted vertical footer segment" id="rodape">
    <div class="ui container">
        Denuncie!
    </div>
</div>
<!-- #RODAPÉ -->
</body>
</html>